site_name: Python tools for the Polylith Architecture

repo_url: https://github.com/DavidVujic/python-polylith
repo_name: DavidVujic/python-polylith

nav:
    - "What's Polylith?": index.md
    - Installation: installation.md
    - Setup: setup.md
    - Commands: commands.md
    - Configuration: configuration.md
    - "The Polylith Workspace": workspace.md
    - Dependencies: dependencies.md
    - "Projects & pyproject.toml": projects.md
    - Testing: testing.md
    - "Packaging & deploying": deployment.md
    - "Migrating to Polylith": migrating.md
    - Examples: examples.md
    - "Videos & tutorials": videos.md
    - "Configuring your Python IDE": ide.md

theme:
  features:
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy

  name: material

  icon:
    repo: fontawesome/brands/github

  logo: img/polylith-logo.png
  favicon: img/polylith-48by48.ico

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DavidVujic/python-polylith
      name: Python tools for the Polylith Architecture on GitHub

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
